# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60129c827609a28d673479c70de3cfd313a7726a7eef4d7d5dc2dc509ec3242332a7a29e5f42ea72ad1733c92eea63dced2a8e95a12e80968d982bca7b0d8d5a

test:
  secret_key_base: e3faf667ff8f6da014ac840c944aa944981b79d8571fc24a041b5da9650571fe5e8e37bfa42b2a8daf92360af4857f3dc1505dc792ec2b697ddbf9154fb86a30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
